function [fitresult, gof] = createFit_1(z, x, y)
%CREATEFIT(Z,X,Y)
%  Create a fit.
%  
%  Data for 'untitled fit 1' fit:
%      X Input : z
%      Y Input : x
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 07-Jun-2017 05:31:41
 

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( z, x, y );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'y vs. z, x', 'Location', 'NorthEast' );
% Label axes
xlabel('z');
ylabel('x');
zlabel('y');
axis tight;
view(3);
axis vis3d image, box on, grid on
camlight, lighting phong, alpha(.8)
zoom on;
zoom(1.009);


