filenameNorm = 'C:\Users\1\Desktop\Учеба\Диплом\Прога\result\data\calculation_norm.txt';
filenameUni ='C:\Users\1\Desktop\Учеба\Диплом\Прога\result\data\uniform_new_new.txt';
beginDepth = 50;
endDepth  = 1300;
step = 2;
n = (endDepth - beginDepth)/step;
pNorm = zeros(1, n);
pUni = zeros(1, n);
depth =linspace(beginDepth,endDepth,n);
for i = 1:1:n
    pNorm(i) = dissectDataWithBreakeage(filenameNorm,depth(i));
    pUni(i) = dissectDataWithBreakeage(filenameUni,depth(i));
end
depth =linspace(beginDepth,endDepth,length(pNorm));
[xData, yDataNorm] = prepareCurveData( depth, pNorm );
[xData, yDataUni] = prepareCurveData( depth, pUni );


% Set up fittype and options.
ft = fittype( 'poly7' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult_norm, gof_norm] = fit( xData, yDataNorm, ft, opts );
[fitresult_uni, gof_uni] = fit( xData, yDataUni, ft, opts );


% Plot fit with data.

figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;
h_norm = plot( xData,fitresult_norm(xData));
h_uni = plot( xData,fitresult_uni(xData));
set(h_norm                          , ...
    'LineWidth'       , 2);
set(h_uni                          , ...
    'LineWidth'       , 2,...
    'Color' ,'r');
hTitle  = title ('Зависимость вероятности пробития от глубины пробития');
hXLabel = xlabel('Глубина пробития   (мм)'                     );
hYLabel = ylabel('Вероятность  (--/--)'                      );
hLegend = legend( ...
    [h_norm, h_uni], ...
    'Нормальное распределение' , ...
    'Равномерное распределение', ...
    'location','SouthEast');


set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , 0:0.1:1, ...
    'LineWidth'   , 1         );
axis tight;
grid on;